name: Build Windows Installers

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        arch: [x86, x64]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        architecture: ${{ matrix.arch }}

    - name: Install PyInstaller
      run: pip install pyinstaller

    - name: Install client requirements
      run: pip install -r requirements-client.txt

    - name: Install server requirements
      run: pip install -r requirements-server.txt

    - name: Build Client
      run: pyinstaller --onefile --noconsole Cliente/client_app.py --name Cliente_${{ matrix.arch }}

    - name: Build Server
      run: pyinstaller --onefile --noconsole Servidor/server.py --name Servidor_${{ matrix.arch }}

    - name: Upload installers
      uses: actions/upload-artifact@v4
      with:
        name: installers-${{ matrix.arch }}
        path: dist/*

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: "Gestor Inventario Repuestos v1.0.${{ github.run_number }}"
        files: dist/*
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
